### ISSUE TITLE
Fix deadlock in Basic/ChannelTest.FactoryIsNotJoined

### ISSUE THREAD

**Issue by beauby** [pytorch/tensorpipe#118]
Accept callback is never called in `Basic/ChannelTest.FactoryIsNotJoined` on OSX. This is the reason why `ctest -R Basic/ChannelTest.FactoryIsNotJoined/0` hangs.

Edit: The issue seems to be that the connection is being destroyed before being established, hence the accept callback is never fired.

Minimal example:
```
TEST_P(TransportTest, UVHangs) {
  testConnection(
      [&](std::shared_ptr<transport::Connection> conn) {
        std::cerr << "foo" << std::endl;
      },
      [&](std::shared_ptr<transport::Connection> conn) {
        std::cerr << "bar" << std::endl;
      });
}
```

**Comment by heiner** [comment]
This appears to be the same issue:

Following the README on my MacBook, then running tensorpipe/test/tensorpipe_test hangs at `[ RUN ] Basic/ChannelTest.contextIsNotJoined/0` (pretty reliably).

Running with `TP_VERBOSE_LOGGING=9` does not hang typically, which seems to indicate some kind of race?

I managed to get it to hang with verbose logging and got the backtraces of the threads with lldb. Outputs in this gist: https://gist.github.com/heiner/eda54649104500ec23ddfa887a276619

My system:
OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.17.2
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0

**Comment by heiner** [comment]
Can confirm this does fix the issue.
