### ISSUE TITLE
What's the expected interaction of this with NCCL when using data parallelism?

### ISSUE THREAD

**Issue by deepakn94** [pytorch/tensorpipe#192]
This is a cool project!

I was wondering what the expected interaction of TensorPipe is with NCCL used for data parallelism, especially given [this limitation](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/communicators.html#using-multiple-nccl-communicators-concurrently).

**Comment by lw** [comment]
We are investigating whether a NCCL-based channel could be feasible but, as you point out, it is likely to incur in issues. Even if it worked, it might be "awkward" and underperforming as we'd be wrapping a blocking API in an asynchronous library. Therefore, long-term, we'll probably want to roll our own GPUDirect implementation, but that's harder to get right. So we'll see...

**Comment by deepakn94** [comment]
Makes sense! Thanks!
