### ISSUE TITLE
Merge utils/ subdir into common/

### ISSUE THREAD

**Issue by lw** [pytorch/tensorpipe#241]
There's no strong reason for keeping them separate. I think we used to do that because the files in utils were copied from other repos, whereas the ones in common were "original", but we've now modified the former to a point where they're unrecognizable. Moreover we've added dependencies between the two (e.g., Segment, in util, depends on Socket, in common; and RingBufferReadOperation, in common, depends on RingBuffer, in util). So in fact we have a cyclical dependency, which only works because of a lucky include order. We should just put everything in common to everything clearer and simpler.

**Comment by beauby** [comment]
Closing, as this is done.
