### ISSUE TITLE
short read: got 2147479552 bytes while expecting to read 2560000000 bytes

### ISSUE THREAD

**Issue by pbelevich** [pytorch/tensorpipe#301]
I used RPC+tensorpipe to train a network with a layer of size `250k * 2560 * sizeof(float) = 2560000000`:

```
[W tensorpipe_agent.cpp:756] RPC agent for worker8 encountered error when reading incoming request from master: short read: got 2147479552 bytes while expecting to read 2560000000 bytes

```

Does RPC has any limitation on the number of bytes to send/receive?

**Comment by lw** [comment]
Thanks for flagging this! I search a bit and found out this:

> On Linux, read() (and similar system calls) will transfer at most 0x7ffff000 (2,147,479,552) bytes, returning the number of bytes actually transferred.  (This is true on both 32-bit and 64-bit systems.)

https://man7.org/linux/man-pages/man2/read.2.html

(The same applies to write)

Hence I guess we need to audit all our read and write calls to ensure they're split into chunks if they are too large.

**Comment by lw** [comment]
Fixed in https://github.com/pytorch/tensorpipe/commit/7d72e62c6a3833f6030dcdf08a43938d84c19f61.
