### ISSUE TITLE
CMake: public headers are not installed

### ISSUE THREAD

**Issue by SpaceIm** [pytorch/tensorpipe#317]
public headers installation is missing in install target

**Comment by lw** [comment]
Yeah we were already tracking this in #104 (which, as you can see, is rather old). We're all in favor of doing this, but so far it hasn't proven to be critical, as PyTorch (the main user of TensorPipe) managed to work anyways. PyTorch also restricts which versions of CMake we can support (I believe we must be compatible with CMake 3.5). TBH, we probably won't get to it shortly, but if you're willing to contribute a pull request for it it would be very much appreciated!

**Comment by SpaceIm** [comment]
I see. https://github.com/pytorch/tensorpipe/issues/104 is slighlty different.

I can submit a PR when I have time.
Since I'm currently packaging libtorch and all its dependencies in conan package manager, including tensorpipe, I prefer that underlying build system of each lib was responsible of installation, so I'll have to fix this at some point.

For the moment, for tensorpipe we copy all headers of these folders:
- `tensorpipe`
- `tensorpipe/channel`,
- `tensorpipe/common`
- `tensorpipe/core`
- `tensorpipe/transport`
- `tensorpipe/util`

**Comment by lw** [comment]
Yes, indeed #104 is a bit different, but I think the solution is related: currently CMake isn't aware of any headers, hence they can only be fetched from the source directory. We'd need to start tracking headers in CMake, and if we do so we can very easily specify which ones must be copied to the install directory.

We are already required to do so in our internal build system, and there we distinguish between private and public headers. (Private means it's only needed to build our own .cc files, public means it must be installed as it's transitively included by `tensorpipe/tensorpipe.h`). Based off that, I compiled a list of our current public headers:
- `channel/context.h`
- `channel/cpu_context.h`
- `channel/error.h`
- `channel/cuda_context.h` (only when building with CUDA)
- `channel/*/error.h`
- `channel/*/factory.h`
- `common/cpu_buffer.h`
- `common/error.h`
- `common/cuda_buffer.h` (only when building with CUDA)
- `core/buffer.h`
- `core/context.h`
- `core/error.h`
- `core/listener.h`
- `core/message.h`
- `core/pipe.h`
- `transport/context.h`
- `transport/error.h`
- `transport/*/error.h`
- `transport/*/factory.h`
- `transport/*/utility.h`

If you (or anyone else) plans to add this information to our CMake, it would be good to keep this distinction.

**Comment by SpaceIm** [comment]
Sure it's always better to be clear on public/private headers
