### ISSUE TITLE
torch.distributed.rpc.init_rpc on a multiple-GPU machine using Kubernetes

### ISSUE THREAD

**Issue by xbfu** [pytorch/tensorpipe#392]
Hi,

I encountered an error when I tried to run `rpc.init_rpc` on a 4-GPU machine (node-0) using Kubernetes.
The code for initializing is as follows.

```
import os
import argparse

import torch
import torch.distributed.rpc as rpc
import logging

def run(rank, world_size):
    logging.basicConfig(level=logging.INFO)
    options = rpc.TensorPipeRpcBackendOptions(num_worker_threads=8, rpc_timeout=20)
    
    if rank == 0:
        logging.info(f"PS{rank} initializing")
        rpc.init_rpc(f"PS{rank}", rank=rank, world_size=world_size, rpc_backend_options=options)
        logging.info(f"PS{rank} initialized")
    else:
        logging.info(f"Worker{rank} initializing")
        rpc.init_rpc(f"worker{rank}", rank=rank, world_size=world_size, rpc_backend_options=options)
        logging.info(f"Worker{rank} initialized")

    rpc.shutdown()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train VGG on CIFAR10 under synchronous strategy")
    parser.add_argument("--rank", type=int, default=1, help="Global rank of this process.")
    parser.add_argument("--world_size", type=int, default=2, help="Number of world size.")
    parser.add_argument("--master_addr", type=str, default="localhost", help="Address of master.")
    parser.add_argument("--master_port", type=str, default="29600", help="Port that master is listening on.")

    args = parser.parse_args()

    os.environ['MASTER_ADDR'] = args.master_addr
    os.environ['MASTER_PORT'] = args.master_port

    run(args.rank, args.world_size)
```

The yaml file I am using is as follows.

``` bash
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    run: test
spec:
  selector:
    run: test
  ports:
    - protocol: TCP
      port: 29600
      targetPort: 29600
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: test
  name: ps
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
        - name: test
          image: myimage/test:v2
          command: ["python3"]
          args: ["/workspace/measurement/test_init.py","--rank=0","--master_addr=test","--world_size=2"]
          ports:
            - containerPort: 29600
          volumeMounts:
            - name: mydir
              mountPath: /workspace/measurement
      nodeSelector:
        kubernetes.io/hostname: node-0
      volumes:
        - name: mydir
          hostPath:
            path: /home/ubuntu/measurement
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: test
  name: worker1
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
        - name: test
          image: myimage/test:v2
          command: ["python3"]
          args: ["/workspace/measurement/test_init.py","--rank=1","--master_addr=test","--world_size=2"]
          ports:
            - containerPort: 29600
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: mydir
              mountPath: /workspace/measurement
      nodeSelector:
        kubernetes.io/hostname: node-0
      volumes:
        - name: mydir
          hostPath:
            path: /home/ubuntu/measurement
      restartPolicy: Never
```

I got an error on the worker pod:

`
INFO:root:Worker1 initializing
terminate called after throwing an instance of 'std::runtime_error'
  what():  In mapUuidsToGlobalIndices at /opt/conda/conda-bld/pytorch_1616554793803/work/third_party/tensorpipe/tensorpipe/channel/cuda_ipc/context_impl.cc:215 "iter == globalUuids.end()Couldn't find GPU #0 with UUID 4a97e8ca-5d1b-6d82-82cb-11f1cf44943e"
`

I tried to run `python test_init.py --rank=0 --world_size=2` and `python test_init.py --rank=1 --world_size=2` (not using Kubernetes) and It worked well.
I also tried it on a single-GPU machine (node-1) using Kubernetes and it also worked.

Here are the sorftwares I use.
``` bash
ubuntu 18.04
python 3.8.8
torch 1.8.1
kubernetes 1.21.1
docker 20.10.2
```

Any help will be appreciated!

**Comment by xbfu** [comment]
@lw Are some of my settings incorrect? Thank you so much.

**Comment by lw** [comment]
It seems you're using PyTorch 1.8.1, we didn't officially support CUDA in RPC back then (it was a hidden prototype feature, with several known bugs). I could try to debug this failure but I don't think it would be of much use, because we've already changed/fixed that code a lot since. Are you able to pick one of the 1.9 release candidates and try it out?

**Comment by lw** [comment]
Also, I've never used Kubernetes, but containers have always proven a bit problematic because they challenge some of our assumptions. We've tested on Docker the best we can but there are likely bugs left. One thing we know we don't support is "virtual" GPUs, what NVIDIA calls Multi-Instance GPUs (MIG). Is this something you're using?

**Comment by xbfu** [comment]
> Also, I've never used Kubernetes, but containers have always proven a bit problematic because they challenge some of our assumptions. We've tested on Docker the best we can but there are likely bugs left. One thing we know we don't support is "virtual" GPUs, what NVIDIA calls Multi-Instance GPUs (MIG). Is this something you're using?

Thanks for your reply. I can try with torch-1.9. Is torch 1.9 available on Docker Hub? The latest release I can find is torch-1.8.1 on Docker Hub. As for MIG, I've never used it before. I use k8s-device-plugin to support NVIDIA GPUs on Kubernetes. It works well on a single-GPU machine but fails on a multiple-GPU machine.

**Comment by lw** [comment]
I don't think you'll find 1.9 on any "standard" channels because it hasn't been released yet (it will happen in a few days). Until then you need to use the "preview" channels. For example, with conda: `conda install -y -c pytorch-test pytorch`. Or for pip: `pip install -f https://download.pytorch.org/whl/test/cu111/torch_test.html torch`.

You can also use the nightlies if that's more convenient, though be aware that they're "even newer" than 1.9, and thus less tested.

**Comment by xbfu** [comment]
> I don't think you'll find 1.9 on any "standard" channels because it hasn't been released yet (it will happen in a few days). Until then you need to use the "preview" channels. For example, with conda: `conda install -y -c pytorch-test pytorch`. Or for pip: `pip install -f https://download.pytorch.org/whl/test/cu111/torch_test.html torch`.
> 
> You can also use the nightlies if that's more convenient, though be aware that they're "even newer" than 1.9, and thus less tested.

Yes, I download torch 1.9.0+cu111 from your link. It works on a multiple-GPU machine. Thank you so much!

**Comment by lw** [comment]
Awesome, glad we sorted this out!
