### ISSUE TITLE
Does tensorpipe support pure-CPU initialization?

### ISSUE THREAD

**Issue by HuYang719** [pytorch/tensorpipe#393]
Dear tensorpipe team, I am trying to write an async RPC program for pure-CPU processors. However, the error message tensorpipe does not support initialization without CUDA devices. Any solution about running tensorpipe in a pure-CPU host?
Thank you very much!

**Comment by lw** [comment]
You're gonna have to give us more details: what code are you running, and what error are you getting?

**Comment by HuYang719** [comment]
Hi, I try to run the following code on AWS t3.medium (without GPU devices) This code is about doing inference on CPU, and the error occurs when initiating the RPC background with tensorpipe. 

```py
def run_worker(rank, world_size, num_split):
    os.environ['MASTER_ADDR'] = '172.31.3.209'
    os.environ['MASTER_PORT'] = '29501'


    options = rpc.TensorPipeRpcBackendOptions(num_worker_threads=256,rpc_timeout=3000)
    
    if rank == 0:
        rpc.init_rpc(
            "worker0",
            rank=rank,
            world_size=world_size,
            rpc_backend_options=options
        )
        run_master(num_split)
    else:
        rpc.init_rpc(
            "worker1",
            rank=rank,
            world_size=world_size,
            rpc_backend_options=options
        )
        pass


    # block until all rpcs finisha
    rpc.shutdown()
```

and the error message is :

Traceback (most recent call last):
  File "pipe_hug_transformer.py", line 229, in <module>
    run_worker(rank, world_size, num_split)
  File "pipe_hug_transformer.py", line 213, in run_worker
    rpc_backend_options=options
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 194, in init_rpc
    _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 236, in _init_rpc_backend
    rpc_backend_options=rpc_backend_options,
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/distributed/rpc/backend_registry.py", line 99, in init_backend
    return backend.value.init_backend_handler(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/distributed/rpc/backend_registry.py", line 278, in _tensorpipe_init_backend_handler
    api._init_rpc_states(agent)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 116, in _init_rpc_states
    _set_and_start_rpc_agent(agent)
**RuntimeError: In create at /pytorch/third_party/tensorpipe/tensorpipe/common/cuda_lib.h:105 "lib.init(0)(100) CUDA_ERROR_NO_DEVICE (no CUDA-capable device is detected)"**

The code is design for pure-CPU and I could run the code successfully on g4dn.xlarge (with 1 GPU) and force the code use CPU. I wonder the is there any solution to initiate the tensorpipe background for only CPU environments? 

Thank you very much!

**Comment by lw** [comment]
What version of PyTorch are you running? (1.8, 1.9, nightly?) Through which channel are you installing it?

I'm asking because we do definitely support running on CPU-only machines, and this is something that we test regularly in CI. Hence something must be up...

**Comment by HuYang719** [comment]
HI I use PyTorch 1.8.1 version. It is provided by AWS Deep Learning AMI (Ubuntu 18.04) Version 44.0 . 
```bash
Conda activate pytorch_latest_p37
>>> print(torch.__version__)
1.8.1+cu111
```

**Comment by lw** [comment]
Ok thanks I'll take a look at this, however I don't think I can do much to fix the old 1.8.1 version. Any fix would at best become available in 1.9.1.

To get you unblocked though there are a few things you can try:
- You said you are on a CPU-only machine though apparently you do have CUDA driver installed, and this is tripping off TensorPipe. If you are able to do so, you could consider uninstalling the driver and retrying.
- You downloaded and installed a CUDA-enabled version of PyTorch (i.e., see the `+cu111` prefix). There exist CPU-only versions of PyTorch which wouldn't even look for the presence of CUDA and thus wouldn't hit this bug. If you're able to use one of those this should too fix your problem.

**Comment by HuYang719** [comment]
That's great! Thanks for your reply, let me try it then!

**Comment by jirayupiwon1** [comment]
CODE_OF_CONDUCT.md

**Comment by HuYang719** [comment]
Thank you very much! After changing to the PyTorch-CPU environment, everything could run perfectly!
