### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/tensorpipe#395]
I'm writing a [Spack](https://spack.io) package for TensorPipe but I'm encountering a build issue on Ubuntu 18.04 with GCC 7.5.0. Specifically, I see:
```console
$ 'ninja' '-j12' '-v'
[1/54] /home/t-astewart/spack/lib/spack/env/gcc/g++  -I/tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src -I. -I/tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/third_party/libnop/include -O2 -g -DNDEBUG -std=gnu++14 -MD -MT tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o -MF tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o.d -o tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o -c /tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/tensorpipe/channel/helpers.cc
FAILED: tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o 
/home/t-astewart/spack/lib/spack/env/gcc/g++  -I/tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src -I. -I/tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/third_party/libnop/include -O2 -g -DNDEBUG -std=gnu++14 -MD -MT tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o -MF tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o.d -o tensorpipe/CMakeFiles/tensorpipe.dir/channel/helpers.cc.o -c /tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/tensorpipe/channel/helpers.cc
In file included from /tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/tensorpipe/channel/helpers.h:15:0,
                 from /tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/tensorpipe/channel/helpers.cc:9:
/tmp/t-astewart/spack-stage/spack-stage-tensorpipe-master-j3hkh2mab4pdrhqdhrhksslz6bnv4fkw/spack-src/tensorpipe/common/nop.h:11:10: fatal error: nop/serializer.h: No such file or directory
 #include <nop/serializer.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
Here is the full build log:

* [spack-build-out.txt](https://github.com/pytorch/tensorpipe/files/6652513/spack-build-out.txt)

Any idea what I'm doing wrong?

P.S. Would anyone be interested in being listed as a maintainer for TensorPipe? You don't have to know anything about Spack, it just gives us someone to ping when a user reports a build issue or wants to change the build recipe.

**Comment by beauby** [comment]
It looks like you did not check out the submodules. Did you clone with `git clone --recursive https://github.com/pytorch/tensorpipe`?

**Comment by adamjstewart** [comment]
Ah, a rookie mistake. If I check out the submodules I get a bit further, but I get a new error:
```
/tmp/t-astewart/spack-stage/spack-stage-tensorpipe-2021-03-04-az6zj7ay7y45hixz4zao5idjwd2s2y6o/spack-src/tensorpipe/transport/uv/uv.h:364:20: error: 'UV_MAXHOSTNAMESIZE' was not declared in this scope
   std::array<char, UV_MAXHOSTNAMESIZE> hostname;
                    ^~~~~~~~~~~~~~~~~~
```
Full build log:

* [spack-build-out.txt](https://github.com/pytorch/tensorpipe/files/6656749/spack-build-out.txt)

**Comment by adamjstewart** [comment]
The above error seems to only occur on Ubuntu 18.04 with GCC 7.5.0. On macOS 10.15.7 with Apple Clang 12.0.0 I'm able to successfully install TensorPipe.

**Comment by lw** [comment]
You probably have a version of libuv installed on your system which is too old but which is picked up by TensorPipe and used instead of the submodule we provide. You can either upgrade your installed libuv (though unfortunately I don't think we track the minimum supported version) or you can pass the `TP_BUILD_LIBUV` flag to CMake when building TensorPipe to force it to use the submodule.

**Comment by adamjstewart** [comment]
Thanks, that solved my issue! I'll add a `libuv` dependency to our Spack package. If you ever determine the minimum supported version let me know and I can specify that in the build recipe.
