### ISSUE TITLE
Did not find test folder after install with ninja 

### ISSUE THREAD

**Issue by eedalong** [pytorch/tensorpipe#418]
I dont find any test folder after I installed tensorpipe with ninja

**Comment by eedalong** [comment]
![截屏2021-12-11 上午9 39 14](https://user-images.githubusercontent.com/39682259/145659444-5a30e9b5-6735-4e49-b40f-4f578eb87392.png)

here are what I got after installed

**Comment by lw** [comment]
You need to build with `TP_BUILD_TESTING` enabled. You can see how the CI does it:

https://github.com/pytorch/tensorpipe/blob/ed4bbe52b7405d06dd5309cb9b8e647e033b9e00/.circleci/config.yml#L51

**Comment by eedalong** [comment]
Great！ Thx！
