### ISSUE TITLE
Questions regard to source code

### ISSUE THREAD

**Issue by eedalong** [pytorch/tensorpipe#429]
What does this [header_.template](https://github.com/pytorch/tensorpipe/blob/52791a2fd214b2a9dc5759d36725909c1daa7f2e/tensorpipe/common/ringbuffer_role.h#L65) mean?

**Comment by lw** [comment]
It's an uncommon but required usage of the `template` keyword:

> Inside a template definition, `template` can be used to declare that a [dependent name](https://en.cppreference.com/w/cpp/language/dependent_name) is a template.

https://en.cppreference.com/w/cpp/keyword/template

The reason is quite technical and I'm not sure I can fully explain it, so it's best to just go read that reference.

**Comment by eedalong** [comment]
Wow, MAGIC! Respect!
