### ISSUE TITLE
Is IB now only supporting CUDA_GDR now ?

### ISSUE THREAD

**Issue by eedalong** [pytorch/tensorpipe#430]
I found there are Transport based on IB but only find CUDA_GDR in channels, so IB mode doesnt support CPU tensors's transfer right now ?

**Comment by eedalong** [comment]
So we transfer payloads/meta by IB transport and transfer tensors by GDR?

**Comment by lw** [comment]
CPU tensors can be transferred over IB using the `basic` channel, which allows any transport to be used also as a CPU channel, thus leveraging the `ibv` transport.

Thus, yes, descriptors, metadata, payloads and CPU tensors will be transferred over the `ibv` transport, whereas CUDA tensors will be transferred over `cuda_gdr`.

**Comment by eedalong** [comment]
Great！Appreciate your detailed answer!
