### ISSUE TITLE
libnop dependency changes

### ISSUE THREAD

**Issue by themarpe** [pytorch/tensorpipe#433]
Hi @lw 

Saw that your project also uses libnop - as I wasn't successful in getting the changes back to mainline, we have our own fork that we improve upon. 

https://github.com/luxonis/libnop/tree/develop

Most pertinent changes: 
 - CMake support (examples & test suite also)
 - Some warnings fixes
 - MSVC support for both conforming and non-conforming preprocessor

Let me know if the changes are of any help to this project.

**Comment by lw** [comment]
Thanks for the information, though we're not having any issues with our current use of libnop (also, not sure why you need to build it: it's a headers-only library) and I'd be more reassured to stick to the official Google version.

**Comment by themarpe** [comment]
Sounds great and understood - if it covers your needs then no need to make modifications.
(The CMake support is there mostly for consumption reasons - find_package, etc...)
