### ISSUE TITLE
Message may be missing if multiple pipes are writing to another same one

### ISSUE THREAD

**Issue by Rhett-Ying** [pytorch/tensorpipe#434]
I have 10 clients and 1 server. If 10 clients are sending message **continuously** to the server via pipe. The `pipe->write(msg, [](error){if(error)(log_fatal....)})` did not fail, but such messages cannot be received in server side(`pipe->readDescriptor([](error, descriptor){...})`). `error` in server's pipe is not evaluated as `true`.

a few details:
`context->registerTransport(0, "uv", tensorpipe::transport::uv::create())`
`context->registerChannel(0, "basic", tensorpipe::channel::basic::create());`

In the beginning, it works well. but a few moments later, messages are missing.

I tried with `TP_VERBOSE_LOGGING=10` and no obvious error is printed.

any clue for such phenomenon? is it caused by sending messages too rapidly and caused congestion? or underlying buffer is overflowed.

BTW, if `pipe->write(msg)` failed, could I try to re-send the `msg`? `msg` object is still available for re-send? or `msg` is moved and cannot be re-used any more?

**Comment by lw** [comment]
Can you provide a minimal repro?

**Comment by Rhett-Ying** [comment]
I have many threads(16) shown below which keeps sending messages, do I need to add a promise and wait on the future in main thread? If I wait on the future, msg has already been written into kernel buffer when wait() returns? If not wait on the future, msg will be queued and sent asyncly?

`void Send(){tp::Message msg;
auto done = std::make_shared<std::promise<void>>();
pipe->write(msg, [done](const Error& error){
            if(error){throw std::runtime_error(error.what());}
            done->set_value();
        });
done->get_future().wait();}`

` for(int i = 0; i<1000; ++i){Send();}`

**Comment by lw** [comment]
If you don't give me a full self-contained repro there's hardly anything I can do for you.

One thing I can point out though is that you're raising an exception within the callback, but that exception will just bubble up to TensorPipe and be swallowed (or, worse, crash some internal TensorPipe component). You should find another way to propagate errors, for example using `done->set_exception(std::make_exception_ptr(std::runtime_error(error.what())))`.

**Comment by Rhett-Ying** [comment]
Thanks for pointing out the issue in my snippet. I am working on the minimal self-contained repro. will get back once ready.

**Comment by Rhett-Ying** [comment]
root cause is found, not related to tensorpipe. thanks for your helps.
