### ISSUE TITLE
tensorpipe/transport/ibv/reactor.cc:132 "Unknown opcode: 136"

### ISSUE THREAD

**Issue by eedalong** [pytorch/tensorpipe#436]
I use pytorch rpc, sometimes it gives me this error. And I always get error from rank0

**Comment by eedalong** [comment]
I try to send cuda tensors over IB and sometimes it works, sometimes just desnt

**Comment by eedalong** [comment]
BTW, how can I check if I can use cuda_gdr between 2 endpoints?

**Comment by eedalong** [comment]
V0327 07:52:54.252611 2716381 tensorpipe/core/context_impl.cc:81] Context worker0 is registering transport ibv
V0327 07:52:54.252761 2716381 tensorpipe/core/context_impl.cc:81] Context worker0 is registering transport uv
V0327 07:52:54.261135 2716381 tensorpipe/core/context_impl.cc:81] Context worker0 is registering transport shm
V0327 07:52:54.261295 2716381 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cuda_basic
V0327 07:52:54.262006 2716381 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cuda_xth
V0327 07:52:54.262173 2716381 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cma
V0327 07:52:54.276424 2716381 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cuda_ipc
V0327 07:52:54.276447 2716381 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel basic
V0327 07:52:54.278730 2716381 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel mpt_uv

I saw that I am using registering these channels and transports when I init rpc, I didnt see cuda_gdr here, is it because my machine dosnt support gdr?

**Comment by eedalong** [comment]
@lw

**Comment by lw** [comment]
What version of PyTorch are you using? I landed some fixes to IBV and GDR back in November which might help here (not fully sure), so please see if this issue still happens with PyTorch 1.11.

**Comment by eedalong** [comment]
I am using stable version 1.10

**Comment by lw** [comment]
PyTorch 1.10 was released in October 2021, hence before my fixes. Could you try with PyTorch 1.11, which is now stable as well?

**Comment by eedalong** [comment]
ook， let me try it

**Comment by eedalong** [comment]
Seems pytorch1.11 indeed solves this `unknown opCode `problem. What about useage of cuda_gdr? @lw

**Comment by lw** [comment]
> What about useage of cuda_gdr?

What do you mean? Are you encountering any issues with CUDA_GDR on PyTorch 1.11? The fixes I landed back in November were applied to both IBV and CUDA_GDR.

**Comment by eedalong** [comment]
V0329 14:20:06.788888 3594725 tensorpipe/core/context_impl.cc:81] Context worker0 is registering transport ibv
V0329 14:20:06.794667 3594725 tensorpipe/core/context_impl.cc:81] Context worker0 is registering transport shm
V0329 14:20:06.794791 3594725 tensorpipe/core/context_impl.cc:81] Context worker0 is registering transport uv
V0329 14:20:06.795027 3594725 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cuda_basic
V0329 14:20:06.795670 3594725 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cuda_xth
V0329 14:20:06.809282 3594725 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cuda_ipc
V0329 14:20:06.824053 3594725 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel mpt_uv
V0329 14:20:06.824344 3594725 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel cma
V0329 14:20:06.824370 3594725 tensorpipe/core/context_impl.cc:104] Context worker0 is registering channel basic

Still I didnt see cuda_gdr channel registered here @lw

**Comment by lw** [comment]
Apparently TensorPipe thinks your system doesn't have the necessary requirements to support CUDA_GDR. You can find out why TensorPipe thinks that by running with `TP_VERBOSE_LOGGING=6`.

**Comment by eedalong** [comment]
ook, thx!

**Comment by eedalong** [comment]
V0406 02:34:00.942715 189776 tensorpipe/channel/cuda_gdr/context_impl.cc:479] CUDA GDR channel is not viable because the nv_peer_mem kernel module isn't active

**Comment by lw** [comment]
There you go, it seems your system is missing the required kernel modules. I'd suggest you check with your system administrator, or just search on Google how to set up those modules. There's not much more I can do as it depends on your system.
