### ISSUE TITLE
Questions regard to IB

### ISSUE THREAD

**Issue by eedalong** [pytorch/tensorpipe#437]
Hi~, I am testing tensorpipe with IB and I found something interesting. 

I have 2 machines, each machine requests some sparse data from another one. For better performance, each machine collects sparse data into a dense vector as result when processing request. Here are 2 different settings

- 1. Use cpu to collect sparse data and send over IB. use transport=IBV, channel=basic
- 2. Use cpu to collect sparse data, move the data to GPU and send over IB, use transport=IBV, channel=cuda_basic

Since setting-2 needs extra memory copy(CPU->GPU and GPU->CPU when sending) so we expect setting-2 gives us worse performance w.r.t setting-1. But the results are opposite, setting-2 gives us 2.3GB/s bandwith and setting-1 gives us 1.9GB/s bandwidth. Do you have any idea on this results? @lw

**Comment by lw** [comment]
I don't see any obvious reason for this. Again if you could share a repro that would really help.

**Comment by eedalong** [comment]
ook, you can [check here](https://github.com/quiver-team/quiver_feature/blob/main/test.py)

This is a private repo and I have invited you to join this repo, check your email if you cannt access the content.

@lw

**Comment by eedalong** [comment]
Preprocess part(request dispatching) and post process part(move data to GPU) may make some difference. Because under the first setting, all preprocess are done in CPU and the 2nd uses GPU.

**Comment by lw** [comment]
I'd prefer if you could extract that to a public self-contained repro. Moreover, if you're saying that your code is behaving differently in those two scenarios, you should try to eliminate those differences in order to make sure it's really TensorPipe's fault.

**Comment by eedalong** [comment]
Ok~. BTW, I am not trying to blame TensorPipe for this, this is a great project and I love it.
