### ISSUE TITLE
Support SHM ringbuffer chunking writes larger than the buffer's size

### ISSUE THREAD

**Issue by lerks** [pytorch/tensorpipe#57]
We have by default a 2MB buffer, which is plenty for the small control messages we expect to send on it. However, to support some corner cases (like messages with millions of tensors, or the SHM transport being used as a channel using the basic channel factory) we may want to implement the ability for writes larger than the buffer's size to be split into chunks which are written separately. This should be transparent to the transport's user.

**Comment by beauby** [comment]
Closing now that #82 was merged.
